### ISSUE TITLE
Error 'An input parameter is already in use.'

### ISSUE THREAD

**Issue by ooijenvangilbert** [martinbjerge/ur-interface#3]
when i start the Example.py i get the following error :
`
2023-10-01 16:19:53,444 - URBasic_robotModelEvent - INFO - Init done
2023-10-01 16:19:53,947 - URBasic_dataLogEvent - INFO - DataLog constructor done
2023-10-01 16:19:54,450 - URBasic_dashboardEvent - INFO - Connected
2023-10-01 16:19:54,450 - URBasic_dashboardEvent - INFO - UR Dashboard respond Connected: Universal Robots Dashboard Server
2023-10-01 16:19:54,451 - URBasic_dashboardEvent - INFO - Dashboard server constructor done
2023-10-01 16:19:54,451 - URBasic_robotConnectorEvent - INFO - Init done
waiting for everything to be ready
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/g/Desktop/ur-interface/URBasic/rtde.py", line 623, in run
    self.__receive()
  File "/home/g/Desktop/ur-interface/URBasic/rtde.py", line 423, in __receive
    data = self.__decodePayload(packet_command, packet)
  File "/home/g/Desktop/ur-interface/URBasic/rtde.py", line 551, in __decodePayload
    input_config = RTDE_IO_Config.unpack_recipe(payload, has_recipe_id)
  File "/home/g/Desktop/ur-interface/URBasic/rtde.py", line 702, in unpack_recipe
    raise ValueError('An input parameter is already in use.')
ValueError: An input parameter is already in use.
waiting for everything to be ready
`
Yesterday the robot worked fine until some moment (not sure what changed there) and now i get this. 
Do you have any idea what is going on?

**Comment by ooijenvangilbert** [comment]
Never mind, i found what is going on.

For reference : under program => installation => Ethernet/IP should be disabled. now it moves fine.
